SELECT * FROM [dbo].[Parties]
SELECT * FROM [dbo].[PartyTypeWrappers]
SELECT * FROM [dbo].[JobPositionWrappers]
SELECT * FROM [dbo].[JobPositionTierOneCategories]
SELECT * FROM [dbo].[JobPositionTierTwoCategories]
SELECT * FROM [dbo].[Schools]
SELECT * FROM [dbo].[Addresses]
SELECT * FROM [dbo].[SchoolDescriptionTypeWrappers]
SELECT * FROM [dbo].[PostedJobPositions]
SELECT * FROM [dbo].[PostedJobPositionCategories]

--DROP TABLE [dbo].[__MigrationHistory]
--DROP TABLE [dbo].[JobPositionWrappers]
--DROP TABLE [dbo].[PartyTypeWrappers]
--DROP TABLE [dbo].[Parties]
--DROP TABLE [dbo].[PostedJobPositions]
--DROP TABLE [dbo].[PostedJobPositionCategories]
--DROP TABLE [dbo].[SchoolDescriptionTypeWrappers]
--DROP TABLE [dbo].[Schools]
--DROP TABLE [dbo].[Addresses]
--DROP TABLE [dbo].[JobPositionTierOneCategories]
--DROP TABLE [dbo].[JobPositionTierTwoCategories]

--Party Linkage
SELECT * FROM [dbo].[Parties]
SELECT * FROM [dbo].[JobPositionWrappers]
SELECT * FROM [dbo].[JobPositionTierOneCategories]
SELECT * FROM [dbo].[JobPositionTierTwoCategories]

--PostedJob Linkage
SELECT * FROM [dbo].[PostedJobPositions]
SELECT * FROM [dbo].[PostedJobPositionCategories]
SELECT * FROM [dbo].[JobPositionTierOneCategories]
SELECT * FROM [dbo].[JobPositionTierTwoCategories]
